### ISSUE TITLE
[1.0.6.1] Job queue becomes stuck if additional jobs queued during downloading

### ISSUE THREAD

**Issue by Akio-kun** [Nandaka/NijieDownloader#23]
I've had a tendency to queue a few jobs, get them started downloading, then go back to the browser and do some more searching and queuing. The program tolerates this beautifully, except that the job queue becomes 'stuck' on the first of any jobs I add after I press Start and the downloads are running.

The program will complete the last of the pre-queued jobs normally, start the next normally by downloading the folder picture....but then hang as soon as it attempts an actual source image. Sometimes it is able to retrieve the the folder image, and sometimes not (checked extant)

The download manager behavior is baffling as well. The stuck job will continue to say Running (with the moving status bar)--but sometimes the Start button will remain pressed as it should, but sometimes it will pause (or stop?) while the Running/status bar still indicate. 

The solution is to simply press Start (or Pause->Resume, depending on the type of failure). After that I did not find any files to be corrupted or missing. 

Here are four clippings of the logs when this happened....probably nothing useful. I believe it stayed stuck on the 'processing image' or maybe 'work date' line as long as I cared to leave it.
http://pastebin.com/rh2qAxiM

**Comment by chronometric** [comment]
This issue that @Akio-kun brought up still seems to be one of the few outstanding problems as of version 1.0.7.7. I haven't experienced any serious freezing as mentioned in the previous post; just the non-continuous batch issue mentioned in the first post. Queue 10 artists, browse and add 10 more while that batch is going, and the job list inevitably halts after the initially queued 10. 

One difference might be that I experience a "clean" stalling: either nothing happens after completion, or the "Job Finished" window pops up, but in either case the new jobs remain in a queued state and can be started by Pause/Resume or Start. Have never seen the endless "running" or cancellation freezing. No corrupted images that I've seen, nor any jobs where only the folder image was downloaded before stalling.

I suppose this is the same behavior that PixivUtil is programmed with...you run a download job, and when it's done you can do more. But the interface is slick enough that it encourages this kind of multitasking, work-while-you-download capability, so I suppose the ideal behavior would be for the running queue to incorporate new jobs. Failing that, getting the "jobs finished" popup consistently would be a good alternative, so you would at least know to nudge the queue.

**Comment by chronometric** [comment]
Haven't noticed this happening in quite a while, I guess my post above was different behavior that seemed potentially related. I've made a new issue #41 for that, so I think this can safely be closed ^^
