### ISSUE TITLE
[1.0.7.0] Minor problem while processing with DB / Table name = NijieTags

### ISSUE THREAD

**Issue by reyaz006** [Nandaka/NijieDownloader#30]
<pre>System.Data.Entity.Infrastructure.DbUpdateException: An error occurred while updating the entries. See the inner exception for details. ---> System.Data.Entity.Core.UpdateException: An error occurred while updating the entries. See the inner exception for details. ---> System.Data.SqlServerCe.SqlCeException: A duplicate value cannot be inserted into a unique index. [ Table name = NijieTags,Constraint name = PK_dbo.NijieTags ]
   in System.Data.SqlServerCe.SqlCeCommand.ProcessResults(Int32 hr)
   in System.Data.SqlServerCe.SqlCeCommand.ExecuteCommandText(IntPtr& pCursor, Boolean& isBaseTableCursor)
   in System.Data.SqlServerCe.SqlCeCommand.ExecuteCommand(CommandBehavior behavior, String method, ResultSetOptions options)
   in System.Data.SqlServerCe.SqlCeCommand.ExecuteNonQuery()
   in System.Data.Entity.SqlServerCompact.SqlCeMultiCommand.ExecuteNonQuery()
   in System.Data.Entity.Infrastructure.Interception.InternalDispatcher`1.Dispatch[TTarget,TInterceptionContext,TResult](TTarget target, Func`3 operation, TInterceptionContext interceptionContext, Action`3 executing, Action`3 executed)
   in System.Data.Entity.Infrastructure.Interception.DbCommandDispatcher.NonQuery(DbCommand command, DbCommandInterceptionContext interceptionContext)
   in System.Data.Entity.Core.Mapping.Update.Internal.DynamicUpdateCommand.Execute(Dictionary`2 identifierValues, List`1 generatedValues)
   in System.Data.Entity.Core.Mapping.Update.Internal.UpdateTranslator.Update()
   ---
   in System.Data.Entity.Core.Mapping.Update.Internal.UpdateTranslator.Update()
   in System.Data.Entity.Core.Objects.ObjectContext.ExecuteInTransaction[T](Func`1 func, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction, Boolean releaseConnectionOnSuccess)
   in System.Data.Entity.Core.Objects.ObjectContext.SaveChangesToStore(SaveOptions options, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction)
   in System.Data.Entity.Core.Objects.ObjectContext.SaveChangesInternal(SaveOptions options, Boolean executeInExistingTransaction)
   in System.Data.Entity.Internal.InternalContext.SaveChanges()
   ---
   in System.Data.Entity.Internal.InternalContext.SaveChanges()
   in NijieDownloader.UI.JobRunner.SaveImageToDB(JobDownloadViewModel job, NijieImage image)</pre>

This can be seen in the log, for several images. There are no problems with files themselves.
Not sure why this happens, and I'm not using any tags in my job list.

**Comment by chronometric** [comment]
[1.0.7.7] I just downloaded that artist with DB on, using concurrent jobs at both 1 and 2. All behavior nominal and nothing abnormal in the log. Guess this kink might have worked itself out?
