### ISSUE TITLE
[1.0.7.6] Invalid URI

### ISSUE THREAD

**Issue by reyaz006** [Nandaka/NijieDownloader#37]
This happens on seemingly random images. Happened >30 times on my batchlist (~4000 members).

<pre>2015-12-24 09:33:20,164 DEBUG [   11] - Downloading url: ... ==> ...
2015-12-24 09:33:20,683 ERROR [   12] - filenameFormat={memberId}\{imageId}{page}_{imageTitle}_{serverFilename}
System.UriFormatException: Invalid URI: The Authority/Host could not be parsed.
   in System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   in Nandaka.Common.Util.ExtractFilenameFromUrl(String url, Boolean stripExtension)
   in NijieDownloader.UI.MainWindow.makeFilename(JobDownloadViewModel job, NijieImage image, Int32 currPage, FilenameFormatType type)</pre>
Usually followed by
<pre>[1003] Failed when renaming</pre>

1.0.7.4 and 1.0.7.5 did not have this problem, as far as I can see from the logs.

I think this error forces the app to stop processing current member job leaving it with Error status.

**Comment by reyaz006** [comment]
Tried to do a second run with "Skip if in DB" disabled, got over 1000 errors like this.

**Comment by TheDoc69** [comment]
I have exactly the same problem. It was working flawlessly before the 1.0.7.5 update.

I tried changing the renaming of files (just {imageId} for example), the folder used by NijieDownloader to save file, http or https mode, etc. but nothing worked.
It happens of more than 80% of the downloads (in my case I use download by tag) and it seems to depend on the image (some images always work, other always fails). 

The strange part it that the image is downloaded on the computer, then the error appears and stop the actual tag downloading. So the image which is causing the error is saved on the computer, but no further downloading is possible. In the case of a manga (several pages), in case of error, the first page only is downloaded.
If it can help you here are some nijie ImageID causing the error for me :  
151422
151302
151411
And some working images : 
151124
151184
151402

**Comment by reyaz006** [comment]
v1.0.7.7 fixed this issue. Thank you so much, @Nandaka !
