### ISSUE TITLE
404 error

### ISSUE THREAD

**Issue by hatabbich** [Nandaka/NijieDownloader#38]
i have 404, time out error, what can it be? help :(

**Comment by Nandaka** [comment]
404 = file not found on the server, nothing can be done. You can try to open the page, but it should show the same error.
Time Out error = retry?

**Comment by chronometric** [comment]
Indeed, in refreshing my collection of artist downloads from about two years ago, I find that many artists delete their old images, and some artists leave altogether. 

I've never seen a 404 or timeout error except when my proxy/network was down, though. Being much more descriptive about where this happened would probably be helpful for Nandaka.

Like he says, go to the webpage to find out if the program or site is causing the error. The pixiv-style URLs make it easy to navigate to both artists and single images.

(Likely basic external error, issue is probably worth closing for housekeeping ;3 )
