### ISSUE TITLE
[1.0.7.9] Remember status of batch jobs between sessions

### ISSUE THREAD

**Issue by photonometric** [Nandaka/NijieDownloader#42]
The batch list saves the list of jobs between sessions, which is great. But it appears that if you don't remove the complete jobs on exit, **all jobs will regain the "Added" status upon program restart**. Doesn't cause problems except wasted time/bandwidth if your settings deal properly with repeat downloads. But it large lists of jobs or large galleries, it could spin its wheels for a long time. 

Might it be fairly easy to save the download state (Added/Queued/Completed) along with the list, or in other settings? It would be neat to save the "message" status text (downloaded/skipped/available) as well, though that's more informational than useful.

**Comment by Nandaka** [comment]
I purposely doesn't keep the download state/message because the image list of that member/tags search might be updated.
