### ISSUE TITLE
[1.0.8] Minor Bug in Naming

### ISSUE THREAD

**Issue by JingJang** [Nandaka/NijieDownloader#43]
Hello, 
Thanks for the tool.

It seems to always add the page number in manga even when I include {page} or {page-}. So I get duplicate.

if rule is `{memberId}\{imageId}{page}`; I would get this "179135_p1_p0.jpg" instead of this "179135_p1.jpg".

**Comment by Nandaka** [comment]
> I would get this "179135_p1.jpg" instead of this "179135_p1.jpg".

?

**Comment by JingJang** [comment]
Typed it wrong. Sorry. 

I would get  "179135_p1_p0.jpg" instead of this "179135_p1.jpg".
