### ISSUE TITLE
nijie.info issue

### ISSUE THREAD

**Issue by hatabbich** [Nandaka/NijieDownloader#48]
hello, there is's no way to download all images from sites without tags or artist ID???
nijie have some rarerly artist whos post only there and its really difficult too view every update day by day.

**Comment by Nandaka** [comment]
You can try to download your bookmarked artists and add it to the batch job.
![image](https://user-images.githubusercontent.com/836867/28600288-b10f0f24-71e3-11e7-9a79-2bfdb8ec32ff.png)

**Comment by hatabbich** [comment]
oh.. ty for suggestion)))
P.S 75151 - my fav loli artist here)

**Comment by Nandaka** [comment]
hahah, I just use existing login from bugmenot 😃
