### ISSUE TITLE
[1.0.8] Error when program start up

### ISSUE THREAD

**Issue by LenKiMo** [Nandaka/NijieDownloader#49]
Windows 10 Pro 1703 64-Bit, Chinese language system

Please see the picture.
The first line of the first picture means "An exception was thrown when a call to a specified type of binding was made to the constructor of the type `NijieDownloader.UI.Mainwindows`."
"在" means "at".

https://i.loli.net/2017/09/06/59afce6f9bee4.png
https://i.loli.net/2017/09/06/59afcf56244b7.png

**Comment by Nandaka** [comment]
Have you install the Microsoft SQL Compact 4.0 SP1
```
Installation
===============
1. Install Microsoft SQL Compact 4.0 SP1 (http://www.microsoft.com/en-sg/download/details.aspx?id=30709)
2. Extract the archive to the desired folder.
3. Run the exe.
```

**Comment by LenKiMo** [comment]
Oh, my fault, sorry about that.
