### ISSUE TITLE
Tag search does not fully complete before completing

### ISSUE THREAD

**Issue by LieXXX** [Nandaka/NijieDownloader#51]
When I do a tag search and add it to a batch, it does not get passed page 1 and stops at page 2. If I start it at page 2 it goes to page 12. If I start at page 12 it goes to page 24.

**Comment by Nandaka** [comment]
please give more information? If possible, also attach the log file in the application folder (e.g. ```log-2017-09-03.txt```)

**Comment by LieXXX** [comment]
My computer rebooted last night with an update. The program seems to be stopping at different points now. I will get you a log when I can.

**Comment by LieXXX** [comment]
[log-2017-10-11.txt](https://github.com/Nandaka/NijieDownloader/files/1376971/log-2017-10-11.txt)

**Comment by Nandaka** [comment]
hmm, it go up to page 16, what is the expected number of page?

Can you save the batch job and upload the xml so I can test on my pc?

**Comment by LieXXX** [comment]
There are over 17000 results. It should go way beyond where the batch stops.
[Touhou.txt](https://github.com/Nandaka/NijieDownloader/files/1380358/Touhou.txt)

**Comment by Nandaka** [comment]
I modified the logic and it able to loop to the last page (in this case 357, ignore the timing as I'm using debug build, so it wont download the actual images.)
![image](https://user-images.githubusercontent.com/836867/31536430-29815b48-b031-11e7-88df-2be6ab88d1a7.png)

I'm not sure why it doesn't get the whole 17118, maybe it got private images not listed in the search result?

**Comment by Nandaka** [comment]
Try the new version (overwrite the old files) in the /releases

**Comment by LieXXX** [comment]
The fix is working.
