### ISSUE TITLE
404 error, page not found

### ISSUE THREAD

**Issue by hatabbich** [Nandaka/NijieDownloader#52]
Hello, after November it's seems they change something in design maybe images/members pages too?
app don't download anything 

Log add
[log-2017-11-07.txt](https://github.com/Nandaka/NijieDownloader/files/1451900/log-2017-11-07.txt)

**Comment by Nandaka** [comment]
Is the user still active? I tried with different member id and it shows me the result.
![image](https://user-images.githubusercontent.com/836867/33203024-aa5007fa-d139-11e7-804c-d719126eb49b.png)

**Comment by hatabbich** [comment]
batch download works too??? by tags/caution

**Comment by Nandaka** [comment]
Looks ok from my side.

![image](https://user-images.githubusercontent.com/836867/33792689-7754c436-dce1-11e7-86c0-9109b560e15f.png)
