### ISSUE TITLE
Unable to download mp4 files

### ISSUE THREAD

**Issue by modicon** [Nandaka/NijieDownloader#56]
It seems like you can upload mp4 files to nijie. The downloader cannot download them.

**Comment by Nandaka** [comment]
do you have the image id?

**Comment by modicon** [comment]
This is their announcement that includes a video:
https://nijie.info/view.php?id=256283

I don't know if they can have multiple videos in one post (album).

**Comment by Nandaka** [comment]
try https://github.com/Nandaka/NijieDownloader/releases/tag/v1.0.9.2

**Comment by modicon** [comment]
It worked for me, thank you.
