### ISSUE TITLE
Batch Job Downloads to Nonexistent Location

### ISSUE THREAD

**Issue by H0tCh0colat3** [Nandaka/NijieDownloader#57]
When doing a batch download, the program appears to be trying to download files to the D drive. I don't have such a drive, so the entire job fails.

![wrong drive letter](https://user-images.githubusercontent.com/32641956/40273718-f70ba92a-5b93-11e8-837c-ff6e613e6713.PNG)

**Comment by Nandaka** [comment]
then change the download location in settings page?

**Comment by H0tCh0colat3** [comment]
Apparently I'm totally blind and somehow missed the settings page entirely. Thank you for the reply.
