### ISSUE TITLE
1.0.9.5 when fetch images page or login, will show error about ssl/tls error

### ISSUE THREAD

**Issue by vanceliu** [Nandaka/NijieDownloader#73]
error message show blow   
**The request was aborted: Could not create SSL/TLS secure channel.**  
maybe some connection issue?  
thanks

**Comment by Nandaka** [comment]
can you open the site from browser (use microsoft edge)? Looks like the isp block the access to nijie.info

**Comment by vanceliu** [comment]
I can access to nijie.info by Microsoft edge and Firefox browser, downloader sometimes can login(need to reopen the program), but almost can't fetch the images

**Comment by Nandaka** [comment]
try to use https://github.com/Nandaka/NijieDownloader/releases/tag/v1.0.9.6?

**Comment by vanceliu** [comment]
sorry for late response, it's working now, 
thanks Nandada.
